/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : JSMin
 #	author : miyako
 #	2016/10/21
 #
 # --------------------------------------------------------------------------------*/



// --- JSMIN
void JSMin(sLONG_PTR *pResult, PackagePtr pParams);
